name: CI

on:
  push:
    branches: "**"
    pull_request:

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-11.0
            swift: "5.5"
          - os: macos-11.0
            swift: "5.6"
          # difficult to get a macos 12 runner on GitHub
          # - os: macos-12.0
          #   swift: "5.5"
          # - os: macos-12.0
          #   swift: "5.6"
          - os: ubuntu-20.04
            swift: "5.5"
          - os: ubuntu-20.04
            swift: "5.6"
    steps:
      - uses: fwal/setup-swift@v1.14.0
        with:
          swift-version: "5.6"
      - run: swift --version
      - uses: actions/checkout@v2

      - name: build
        run: swift build -c release
